# Generated by Django 2.1.7 on 2019-05-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(blank=True, default='', help_text='可用,分隔', max_length=255)),
                ('response', models.CharField(max_length=255)),
            ],
        ),
    ]
